project:
  type: manuscript

execute:
  freeze: auto

format:
  html:
    toc: true
  pdf: default
  #   documentclass: article
  #   colorlinks: true
  #   include-in-header:
  #     - draft/preamble.tex
  #   cite-method: biblatex

# manuscript:
#   notebooks:
#     - notebook: notebooks/temp.qmd
#       title: Temporary Test 

